project:
  type: book
  output-dir: docs

book:
  title: "PATOG Book"
  author: "Arash B. Abadi"
  date: last-modified
  cover-image: images/patog_cover.png
  chapters:
    - index.qmd
    - prerequisites.qmd
    - omics-data.qmd
    - modeling-simulation.qmd
    - integrated-platforms.qmd
    - specialized-topics.qmd
    - additional-resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    code-fold: true
    code-tools: true
    repo-url: https://github.com/arashabadi/patog
    edit-url: https://github.com/arashabadi/patog/edit/main/
    toc: true
    toc-expand: true
    link-external-icon: true
    link-external-newwindow: true
    navbar:
      right:
        - icon: github
          href: https://github.com/arashabadi/patog
        - icon: edit
          href: https://github.com/arashabadi/patog/edit/main/