project:
  type: book
  output-dir: docs

book:
  title: "PATOG Book"
  author: "Arash Abadi"
  date: last-modified
  cover-image: PATOG.png
  chapters:
    - index.qmd
    - single-cell.qmd
    - version-control.qmd
    - git.qmd
    - github.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    code-fold: true
    code-tools: true
    repo-url: https://github.com/arashabadi/patog
    toc: true
    link-external-icon: true
    link-external-newwindow: true 